// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "config.h"

const char DEVICE_LOGIN_NAME[]  = "27a80b79-04eb-4c9a-bc2f-a5dd83e26dea";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPanelHorizontalAngleChange();

CloudAngle panel_Horizontal_Angle;
CloudElectricCurrent solar_Panel_Current;
CloudElectricPotential solar_Panel_Voltage;
CloudPower solar_Panel_Power;
CloudTemperature solar_Panel_Temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(panel_Horizontal_Angle, READWRITE, ON_CHANGE, onPanelHorizontalAngleChange);
  ArduinoCloud.addProperty(solar_Panel_Current, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(solar_Panel_Voltage, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(solar_Panel_Power, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(solar_Panel_Temperature, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
